version: '3'

services:
  reverse-proxy:
    image: traefik:v2.0
    restart: always
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./services/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: traefik
    labels:
      - "traefik.http.routers.api.rule=Host(`traefik.jr.com`)"
      - "traefik.http.routers.api.service=api@internal"
