# FROM php:7.3.7-fpm
#FROM php:7.3.19-fpm-stretch
FROM php:7.3.19-fpm-stretch
# Debian 9（debian:stretch） , Debian 10（debian:buster）, Debian 11 (debian:bullseye) 
# https://hub.docker.com/_/php
# 官方版本默认安装扩展: 
# Core, ctype, curl ,date, domfileinfo, filter, ftp,hash,iconv,zlib,xml,xmlreader,
# json,libxml,mbstring, mysqlnd, openssl, pcre, PDO, pdo_sqlite, Phar, posix, xmlwriter
# readline, Reflection, session, SimpleXML, sodium, SPL, sqlite3, standard, tokenizer,xml
ENV BUILD_TOOLS libfreetype6-dev zlib1g-dev libjpeg62-turbo-dev libpng-dev libz-dev zlib1g
RUN mv /etc/apt/sources.list /etc/apt/sources.list.bak \
    && echo 'deb http://mirrors.163.com/debian/ stretch main non-free contrib' > /etc/apt/sources.list \
    && echo 'deb http://mirrors.163.com/debian/ stretch-updates main non-free contrib' >> /etc/apt/sources.list \
    && echo 'deb http://mirrors.163.com/debian-security/ stretch/updates main non-free contrib' >> /etc/apt/sources.list \
    && apt-get update
#RUN apt-get install -y --no-install-recommends zlib1g zlib1g-dev
RUN apt-get install -y --no-install-recommends libjpeg62-turbo-dev
RUN apt-get install -y --no-install-recommends libpng-dev
RUN apt-get install -y --no-install-recommends libz-dev
RUN apt-get install -y --no-install-recommends libmcrypt-dev
RUN apt-get install -y --no-install-recommends libfreetype6-dev
RUN apt-get install -y --no-install-recommends libmagickwand-dev
# bcmath, calendar, exif, gettext, sockets, dba, 
# mysqli, pcntl, pdo_mysql, shmop, sysvmsg, sysvsem, sysvshm 扩展
RUN docker-php-ext-install -j$(nproc) bcmath calendar exif gettext sockets dba mysqli pcntl pdo_mysql shmop sysvmsg sysvsem sysvshm 

# GD 扩展
RUN apt-get install -y --no-install-recommends ${BUILD_TOOLS} \
    && rm -r /var/lib/apt/lists/* \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd

# imagick 扩展
RUN export CFLAGS="$PHP_CFLAGS" CPPFLAGS="$PHP_CPPFLAGS" LDFLAGS="$PHP_LDFLAGS" \
    && apt-get install -y --no-install-recommends libmagickwand-dev \
#    && rm -r /var/lib/apt/lists/* \
    && pecl install imagick-3.4.4 \
    && docker-php-ext-enable imagick

# mcrypt 扩展 
RUN apt-get install -y --no-install-recommends libmcrypt-dev \
#    && rm -r /var/lib/apt/lists/* \
    && pecl install mcrypt-1.0.2 \
    && docker-php-ext-enable mcrypt

# Memcached 扩展 
#RUN apt-get install -y --no-install-recommends libmemcached-dev zlib1g-dev \
#    && rm -r /var/lib/apt/lists/* \
#    && pecl install memcached-3.1.3 \
#    && docker-php-ext-enable memcached
ADD php-ext/*.gz /
RUN docker-php-ext-install /php_client

# redis 扩展
RUN pecl install redis-5.0.0 && docker-php-ext-enable redis

# opcache 扩展 
RUN docker-php-ext-configure opcache --enable-opcache && docker-php-ext-install opcache

# xdebug 扩展
RUN pecl install xdebug-2.7.2 && docker-php-ext-enable xdebug

# swoole 扩展
RUN pecl install swoole-4.4.0 && docker-php-ext-enable swoole

#RUN apt-get remove -y  libmcrypt-dev libmagickwand-dev libfreetype6-dev zlib1g-dev libjpeg62-turbo-dev libpng-dev libz-dev zlib1g
RUN apt-get remove -y  libmcrypt-dev libmagickwand-dev libfreetype6-dev zlib1g-dev libjpeg62-turbo-dev libpng-dev libz-dev 
# 镜像信息
LABEL Author="Lun"
LABEL Version="2020.06"
LABEL Description="PHP 7.3.7"

